version: "3.7"
volumes:
  shareprod:
services:
  dev:
    volumes:
      - shareprod:/boxfuse-sample-java-war-hello/target/
    build: ./
  prod:
    image: tomcat:9-jre8-alpine
    volumes:
      - shareprod:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"


