version: "3.7"
volumes:
  shareprod:
services:
  dev:
    volumes:
      - shareprod:/boxfuse-sample-java-war-hello/target/
    build: ./
  prod:
    image: tomcat:9.0.62-jdk11-temurin-focal
    volumes:
      - shareprod:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"


